### PR TITLE
WaveBody Interactions from WAMIT data

### PR DESCRIPTION
**Pull request by hamilton8415**
Changes here to install instructions that will be necessary after the hamilton8415/fs_hydrodynamics branch in buoy_sim is merged.  Note similar names between branches and pull requests in both repositories for maximum confusion.

### CODE REVIEW

**Comment by hamilton8415** [comment]
Am interested to know if anyone has insight into why the section numbering keeps resetting to 1. at each line.  See example here: https://osrf.github.io/buoy_entrypoint/pr-preview/pr-37/Tutorials/Install/Install_source/  

Does it locally with mkdocs too...

**Comment by quarkytale** [comment]
Looking into it

**Comment by quarkytale** [comment]
See #39, should solve the issue. That could also be targeted to `main` if `fs_hydrodynamics`  needs more time.

**Review by quarkytale — APPROVED** [review]
LGTM after merging main in and increasing codeblocks spaces

**Pull request merged**
