### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by quarkytale**
- Fixes numbering 
- Updating docs after Dockerfile change

### CODE REVIEW

**Comment by quarkytale** [comment]
So according to PythonMarkdown differences https://python-markdown.github.io/#differences, 4 spaces in multiple paragragh of a list item should fix indexing in the documentation. That solved it locally for me, but not sure why gh-pages still doesn't increment and all stay `1`. Thoughts @mabelzhang?

**Comment by quarkytale** [comment]
Okay seemed to have worked with twice as many spaces for code blocks (8 spaces) than the usual text (4 spaces).

**Comment by mabelzhang** [comment]
I think it makes sense to target this to `main`, and then merge `main` into #37. There are already changes in this PR that are new from `main` that #37 still needs to resolve conflicts with.

**Comment by hamilton8415** [comment]
Thanks for figuring out this numbering issue.  I think mabel's merge strategy seems fine and we could just go ahead and proceed, we will continue to be adjusting these docs so things don't need to be super finalized.

**Review by andermi — CHANGES_REQUESTED** [review]
Unfortulately, some of the backticks are showing up in the code blocks

image

**Review by andermi — APPROVED** [review]
that worked! LGTM

**Pull request merged**
